#pragma once

#define GLFW_INCLUDE_NONE
#include <GLFW/glfw3.h>

enum key
{
	KEY_ESC = GLFW_KEY_ESCAPE,
};

enum mouse_key
{
	MKEY_LEFT   = GLFW_MOUSE_BUTTON_LEFT,
	MKEY_RIGHT  = GLFW_MOUSE_BUTTON_RIGHT,
	MKEY_MIDDLE = GLFW_MOUSE_BUTTON_MIDDLE,
	MKEY_3      = GLFW_MOUSE_BUTTON_3,
	MKEY_4      = GLFW_MOUSE_BUTTON_4,
	MKEY_5      = GLFW_MOUSE_BUTTON_5,
};

enum action
{
	ACTION_PRESS   = GLFW_PRESS,
	ACTION_RELEASE = GLFW_RELEASE,
	ACTION_REPEAT  = GLFW_REPEAT,
};

